#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=nvim
export VISUAL=nvim
export HOMEBREW_GITHUB_API_TOKEN=0f435993071d9ada585c7c614b9ecb5b3426ff1e

# Go
export GOPATH="$HOME/go"
export GOROOT=/usr/local/opt/go/libexec
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$GOROOT/libexec/bin"

# AWS completion
source "/usr/local/share/zsh/site-functions/aws_zsh_completer.sh"

# Aliases
alias ecrlogin='aws-vault exec -n tan-stage -- aws ecr get-login --no-include-email --registry-ids 931640994161 436889630604 | /bin/sh'

# fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# aws-vault
eval "$(aws-vault --completion-script-zsh)"

# gcloud
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/path.zsh.inc'
source '/usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc'

if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi

# direnv
eval "$(direnv hook zsh)"
