#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...
export EDITOR=nvim
export VISUAL=nvim

# Go
export GOPATH="$HOME/go"
export GOROOT=/usr/local/opt/go/libexec
export PATH="$PATH:$GOPATH/bin"
export PATH="$PATH:$GOROOT/libexec/bin"

# AWS completion
source "/usr/local/bin/aws_zsh_completer.sh"
